In [1]:
import numpy as np
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from qiskit_aer import AerSimulator
from qiskit_aer.utils import insert_noise
from pyqsp.angle_sequence import angle_sequence
from qiskit.quantum_info import Kraus
from qiskit_aer.noise import NoiseModel,depolarizing_error

In [5]:
W = QuantumCircuit(1)
x = Parameter('x')
W.rx(-2 * np.arccos(x),0)
W.draw()

┌────────────────┐
q: ┤ Rx(-2*acos(x)) ├
   └────────────────┘

In [37]:
R = QuantumCircuit(1)
R.rz(np.pi/2,0)
R=R.compose(W,[0])
R.rz(-np.pi/2,0)
R.draw()

┌─────────┐┌────────────────┐┌──────────┐
q: ┤ Rz(π/2) ├┤ Rx(-2*acos(x)) ├┤ Rz(-π/2) ├
   └─────────┘└────────────────┘└──────────┘

In [38]:
from qiskit.quantum_info import Operator
Operator(R.assign_parameters([1]))

Operator([[1.+0.j, 0.+0.j],
          [0.+0.j, 1.+0.j]],
         input_dims=(2,), output_dims=(2,))


In [39]:
Operator(W.assign_parameters([0.2]))

Operator([[0.2+0.j       , 0. +0.9797959j],
          [0. +0.9797959j, 0.2+0.j       ]],
         input_dims=(2,), output_dims=(2,))


In [22]:
import scipy

In [29]:
scipy.linalg.expm(-1j * np.pi/4  * np.array([[1,0],[0,-1]])) @ Operator(R.assign_parameters([0.2])).data @ scipy.linalg.expm(1j * np.pi/4  * np.array([[1,0],[0,-1]]))

array([[0.2+0.j       , 0. +0.9797959j],
       [0. +0.9797959j, 0.2+0.j       ]])

In [30]:
Operator(R.assign_parameters([0.2])).data

array([[ 0.2      +0.j, -0.9797959+0.j],
       [ 0.9797959+0.j,  0.2      +0.j]])

In [32]:
Q = QuantumCircuit(1)
x = Parameter('x')
Q.ry(-2 * np.arccos(x),0)
Q.draw()

┌────────────────┐
q: ┤ Ry(-2*acos(x)) ├
   └────────────────┘

In [36]:
Operator(Q.assign_parameters([-0.2])).data

array([[-0.2      +0.j,  0.9797959+0.j],
       [-0.9797959+0.j, -0.2      +0.j]])

In [34]:
scipy.linalg.expm(-1j * np.pi/4  * np.array([[1,0],[0,-1]]))

array([[0.70710678-0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

In [35]:
scipy.linalg.expm(1j * np.pi/4  * np.array([[1,0],[0,-1]]))

array([[0.70710678+0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j]])